"""
Django settings for portifyweb project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^$hp8&63&x!xz6aito9n_dyecbm8m11ct81%1^@!wvx0-0@o)$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
     'social_django',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # for django-allauth
    'allauth',  # django-allauth for authentication
    'allauth.account',  # for handling user accounts
    'allauth.socialaccount',  # for social authentication
    'allauth.socialaccount.providers.google',
      'tinymce',  # to enable Google authentication
    'authentication', 
     'testgoogle' # your custom authentication app
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'portifyweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portifyweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    'social_core.backends.google.GoogleOAuth2',  # For Google login
    'django.contrib.auth.backends.ModelBackend',  # Default backend
]

SITE_ID = 1

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '298679482957-ockbclqrbrd1bhecrfn5k8ebj6orrb1b.apps.googleusercontent.com'

SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'

# Redirect URL after successful login
LOGIN_REDIRECT_URL = 'home'  # Change to the URL you want to redirect to after login

# Logout redirect URL
LOGOUT_REDIRECT_URL = 'home'


# settings.py

import os

STATIC_URL = '/static/'

# Where Django will collect all static files for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Where you will put your static files (CSS, JS, images)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

SOCIALACCOUNT_AUTO_SIGNUP = True
ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'allauth.socialaccount.adapter.DefaultSocialAccountAdapter'

SOCIALACCOUNT_LOGIN_ON_GET = False  # <--- This skips the confirmation page

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'OAUTH_PKCE_ENABLED': True,  # Optional: adds PKCE support
    }
}

ACCOUNT_USERNAME_GENERATOR = 'portifyweb.utils.generate_unique_username'

#SOCIALACCOUNT_ADAPTER = 'portifyweb.adapters.MySocialAccountAdapter'

# settings.py

# Disable username requirement
ACCOUNT_USERNAME_REQUIRED = False

# Ensure email is required for authentication
ACCOUNT_EMAIL_REQUIRED = True

# Define login method (email only)
ACCOUNT_LOGIN_METHODS = ['email']

# Set the field name for username in the default model
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'


# settings.py

# Trust the X-Forwarded-Proto header from Ngrok to identify HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

GOOGLE_CLIENT_ID ='298679482957-ockbclqrbrd1bhecrfn5k8ebj6orrb1b.apps.googleusercontent.com'

SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

GEMINI_API_KEY = "AIzaSyBcN9e7DbsOmKKerD9G5m7Y5QJSGJCNiFM"  # Replace with your actual API key

import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

TIME_ZONE = 'Asia/Kolkata'

GEMINI_API_KEY = "AIzaSyAUuz6fot5HzNS7U6HQsy8yCI900heZy_E"  # Replace with your actual API key