# Generated by Django 5.1.6 on 2025-04-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_googleuser_delete_socialuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='googleuser',
            name='google_email',
        ),
        migrations.RemoveField(
            model_name='googleuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='googleuser',
            name='last_login',
        ),
        migrations.AddField(
            model_name='googleuser',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
