# Generated by Django 5.1.6 on 2025-04-29 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_googleuser_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='googleuser',
            name='user',
        ),
        migrations.AddField(
            model_name='googleuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 29, 21, 0, 7, 856380, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googleuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='googleuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googleuser',
            name='name',
            field=models.CharField(default=datetime.datetime(2025, 4, 29, 21, 0, 18, 557486, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
