# Generated by Django 5.1.6 on 2025-04-29 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_customuser_updated_at_remove_googleuser_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleuser',
            name='email',
            field=models.EmailField(default=datetime.datetime(2025, 4, 29, 21, 5, 11, 697373, tzinfo=datetime.timezone.utc), max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
