# Generated by Django 5.1.6 on 2025-04-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_googleuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleuser',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
