# Generated by Django 5.1.6 on 2025-04-29 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_googleuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleuser',
            name='user',
        ),
    ]
