# Generated by Django 5.1.6 on 2025-05-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_guestsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestsession',
            name='created_at',
        ),
        migrations.AddField(
            model_name='guestsession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestsession',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
