# Generated by Django 5.1.6 on 2025-05-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_remove_guestsession_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestsession',
            name='name',
            field=models.CharField(default='Guest_0000', max_length=255, unique=True),
        ),
    ]
