# Generated by Django 5.1.6 on 2025-05-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_guestsession_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestsession',
            old_name='name',
            new_name='guest_name',
        ),
    ]
