# Generated by Django 5.1.6 on 2025-05-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_rename_name_guestsession_guest_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestsession',
            name='guest_name',
        ),
        migrations.AddField(
            model_name='guestsession',
            name='name',
            field=models.CharField(default='Guest_0000', max_length=255),
        ),
    ]
