# Generated by Django 5.1.6 on 2025-05-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_remove_guestsession_guest_name_guestsession_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestsession',
            name='name',
        ),
    ]
