# Generated by Django 5.1.6 on 2025-05-02 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testgoogle', '0002_project_userprofile_generateddesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='testgoogle.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='user_logos/'),
        ),
        migrations.AlterField(
            model_name='generateddesign',
            name='colors',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='generateddesign',
            name='interests',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='generateddesign',
            name='navbar',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='generateddesign',
            name='navbar_links',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
