# Generated by Django 5.1.6 on 2025-05-02 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testgoogle', '0004_remove_generateddesign_navbar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generateddesign',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hamburger',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='navbar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='portfolio_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='generateddesign',
            name='navbar',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='generateddesign',
            name='navbar_links',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='generateddesign',
            name='colors',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='generateddesign',
            name='interests',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='generateddesign',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testgoogle.userprofile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
