# Generated by Django 5.1.6 on 2025-05-04 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testgoogle', '0009_profiletest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesignPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(blank=True, max_length=7, null=True)),
                ('secondary_color', models.CharField(blank=True, max_length=7, null=True)),
                ('design_style', models.CharField(blank=True, max_length=100, null=True)),
                ('animation_style', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevicePreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devices', models.JSONField(blank=True, null=True)),
                ('hamburger_menu', models.BooleanField(blank=True, default=False, null=True)),
                ('menu_items', models.JSONField(blank=True, null=True)),
                ('navbar', models.BooleanField(blank=True, default=False, null=True)),
                ('navbar_items', models.JSONField(blank=True, null=True)),
                ('footer_social', models.BooleanField(blank=True, default=False, null=True)),
                ('footer_contact', models.BooleanField(blank=True, default=False, null=True)),
                ('footer_enabled', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('board', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('score', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OverallDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('personal_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testgoogle.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('personal_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='testgoogle.personaldetails')),
            ],
        ),
        migrations.RemoveField(
            model_name='generateddesign',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='generateddesign_user',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='googleprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profiletest',
        ),
        migrations.RemoveField(
            model_name='project_user',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='overalldescription',
            name='personal_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testgoogle.personaldetails'),
        ),
        migrations.AddField(
            model_name='experience',
            name='personal_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='testgoogle.personaldetails'),
        ),
        migrations.AddField(
            model_name='education',
            name='personal_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='testgoogle.personaldetails'),
        ),
        migrations.AddField(
            model_name='devicepreferences',
            name='personal_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testgoogle.personaldetails'),
        ),
        migrations.AddField(
            model_name='designpreferences',
            name='personal_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testgoogle.personaldetails'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='personal_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testgoogle.personaldetails'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='personal_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='testgoogle.personaldetails'),
        ),
        migrations.AddField(
            model_name='project',
            name='personal_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='testgoogle.personaldetails'),
        ),
        migrations.DeleteModel(
            name='GeneratedDesign',
        ),
        migrations.DeleteModel(
            name='GeneratedDesign_user',
        ),
        migrations.DeleteModel(
            name='GoogleProfile',
        ),
        migrations.DeleteModel(
            name='Project_user',
        ),
        migrations.DeleteModel(
            name='UserProfile_user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
