# Generated by Django 5.1.6 on 2025-05-04 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testgoogle', '0010_achievement_contactinfo_designpreferences_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldetails',
            old_name='bio',
            new_name='short_bio',
        ),
    ]
