# Generated by Django 5.1.6 on 2025-05-04 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testgoogle', '0011_rename_bio_personaldetails_short_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='skill',
        ),
    ]
