# Generated by Django 5.1.6 on 2025-05-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testgoogle', '0012_rename_name_skill_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='description',
            new_name='achievement',
        ),
    ]
