# Generated by Django 5.1.6 on 2025-05-04 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testgoogle', '0013_rename_description_achievement_achievement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='resume_file',
            new_name='resume',
        ),
    ]
