# Generated by Django 5.1.6 on 2025-05-04 22:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testgoogle', '0014_rename_resume_file_resume_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
