# Generated by Django 5.1.6 on 2025-05-05 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_guestsession_name'),
        ('testgoogle', '0015_alter_personaldetails_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='designpreferences',
            name='guest_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.guestsession'),
        ),
    ]
