# Generated by Django 5.1.6 on 2025-05-05 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_guestsession_name'),
        ('testgoogle', '0016_designpreferences_guest_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='guest_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.guestsession'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='guest_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.guestsession'),
        ),
        migrations.AddField(
            model_name='devicepreferences',
            name='guest_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.guestsession'),
        ),
        migrations.AddField(
            model_name='education',
            name='guest_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.guestsession'),
        ),
        migrations.AddField(
            model_name='experience',
            name='guest_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.guestsession'),
        ),
        migrations.AddField(
            model_name='overalldescription',
            name='guest_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.guestsession'),
        ),
        migrations.AddField(
            model_name='project',
            name='guest_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.guestsession'),
        ),
        migrations.AddField(
            model_name='resume',
            name='guest_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.guestsession'),
        ),
        migrations.AddField(
            model_name='skill',
            name='guest_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.guestsession'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='personal_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testgoogle.personaldetails'),
        ),
        migrations.AlterField(
            model_name='education',
            name='personal_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testgoogle.personaldetails'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='personal_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testgoogle.personaldetails'),
        ),
        migrations.AlterField(
            model_name='project',
            name='personal_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testgoogle.personaldetails'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='personal_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testgoogle.personaldetails'),
        ),
    ]
