# Generated by Django 5.1.6 on 2025-05-05 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_guestsession_name'),
        ('testgoogle', '0017_achievement_guest_session_contactinfo_guest_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='guest_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.guestsession'),
        ),
    ]
