# Generated by Django 5.1.6 on 2025-05-05 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testgoogle', '0018_personaldetails_guest_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='personal_details',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='personal_details',
        ),
        migrations.RemoveField(
            model_name='designpreferences',
            name='personal_details',
        ),
        migrations.RemoveField(
            model_name='devicepreferences',
            name='personal_details',
        ),
        migrations.RemoveField(
            model_name='education',
            name='personal_details',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='personal_details',
        ),
        migrations.RemoveField(
            model_name='overalldescription',
            name='personal_details',
        ),
        migrations.RemoveField(
            model_name='project',
            name='personal_details',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='personal_details',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='personal_details',
        ),
    ]
