# Generated by Django 5.1.6 on 2025-05-05 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testgoogle', '0019_remove_achievement_personal_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='guest_session',
        ),
        migrations.AddField(
            model_name='achievement',
            name='personal_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testgoogle.personaldetails'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='personal_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testgoogle.personaldetails'),
        ),
        migrations.AddField(
            model_name='designpreferences',
            name='personal_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testgoogle.personaldetails'),
        ),
        migrations.AddField(
            model_name='devicepreferences',
            name='personal_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testgoogle.personaldetails'),
        ),
        migrations.AddField(
            model_name='education',
            name='personal_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testgoogle.personaldetails'),
        ),
        migrations.AddField(
            model_name='experience',
            name='personal_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testgoogle.personaldetails'),
        ),
        migrations.AddField(
            model_name='overalldescription',
            name='personal_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testgoogle.personaldetails'),
        ),
        migrations.AddField(
            model_name='project',
            name='personal_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testgoogle.personaldetails'),
        ),
        migrations.AddField(
            model_name='resume',
            name='personal_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testgoogle.personaldetails'),
        ),
        migrations.AddField(
            model_name='skill',
            name='personal_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testgoogle.personaldetails'),
        ),
    ]
