# Generated by Django 5.1.6 on 2025-05-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testgoogle', '0020_remove_personaldetails_guest_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill',
        ),
        migrations.AddField(
            model_name='skill',
            name='skills',
            field=models.TextField(default='[]'),
        ),
    ]
