# Generated by Django 5.1.6 on 2025-05-08 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_guestsession_name'),
        ('testgoogle', '0021_remove_skill_skill_skill_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='guest_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.guestsession'),
        ),
    ]
