# Generated by Django 5.1.6 on 2025-05-10 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testgoogle', '0023_remove_contactinfo_personal_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='personal_details',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='personal_details',
        ),
        migrations.RemoveField(
            model_name='project',
            name='personal_details',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='personal_details',
        ),
    ]
